/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as QuickLogRouteImport } from './routes/quick-log'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as CuotasRouteImport } from './routes/cuotas'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortafolioIndexRouteImport } from './routes/portafolio.index'
import { Route as PortafolioRentaFijaRouteImport } from './routes/portafolio.renta-fija'
import { Route as PortafolioFondosRouteImport } from './routes/portafolio.fondos'
import { Route as PortafolioCriptoRouteImport } from './routes/portafolio.cripto'
import { Route as PortafolioAhorrosRouteImport } from './routes/portafolio.ahorros'
import { Route as PortafolioAccionesRouteImport } from './routes/portafolio.acciones'

const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickLogRoute = QuickLogRouteImport.update({
  id: '/quick-log',
  path: '/quick-log',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CuotasRoute = CuotasRouteImport.update({
  id: '/cuotas',
  path: '/cuotas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioIndexRoute = PortafolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortafolioRoute,
} as any)
const PortafolioRentaFijaRoute = PortafolioRentaFijaRouteImport.update({
  id: '/renta-fija',
  path: '/renta-fija',
  getParentRoute: () => PortafolioRoute,
} as any)
const PortafolioFondosRoute = PortafolioFondosRouteImport.update({
  id: '/fondos',
  path: '/fondos',
  getParentRoute: () => PortafolioRoute,
} as any)
const PortafolioCriptoRoute = PortafolioCriptoRouteImport.update({
  id: '/cripto',
  path: '/cripto',
  getParentRoute: () => PortafolioRoute,
} as any)
const PortafolioAhorrosRoute = PortafolioAhorrosRouteImport.update({
  id: '/ahorros',
  path: '/ahorros',
  getParentRoute: () => PortafolioRoute,
} as any)
const PortafolioAccionesRoute = PortafolioAccionesRouteImport.update({
  id: '/acciones',
  path: '/acciones',
  getParentRoute: () => PortafolioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuotas': typeof CuotasRoute
  '/onboarding': typeof OnboardingRoute
  '/portafolio': typeof PortafolioRouteWithChildren
  '/quick-log': typeof QuickLogRoute
  '/tesoreria': typeof TesoreriaRoute
  '/portafolio/acciones': typeof PortafolioAccionesRoute
  '/portafolio/ahorros': typeof PortafolioAhorrosRoute
  '/portafolio/cripto': typeof PortafolioCriptoRoute
  '/portafolio/fondos': typeof PortafolioFondosRoute
  '/portafolio/renta-fija': typeof PortafolioRentaFijaRoute
  '/portafolio/': typeof PortafolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuotas': typeof CuotasRoute
  '/onboarding': typeof OnboardingRoute
  '/quick-log': typeof QuickLogRoute
  '/tesoreria': typeof TesoreriaRoute
  '/portafolio/acciones': typeof PortafolioAccionesRoute
  '/portafolio/ahorros': typeof PortafolioAhorrosRoute
  '/portafolio/cripto': typeof PortafolioCriptoRoute
  '/portafolio/fondos': typeof PortafolioFondosRoute
  '/portafolio/renta-fija': typeof PortafolioRentaFijaRoute
  '/portafolio': typeof PortafolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cuotas': typeof CuotasRoute
  '/onboarding': typeof OnboardingRoute
  '/portafolio': typeof PortafolioRouteWithChildren
  '/quick-log': typeof QuickLogRoute
  '/tesoreria': typeof TesoreriaRoute
  '/portafolio/acciones': typeof PortafolioAccionesRoute
  '/portafolio/ahorros': typeof PortafolioAhorrosRoute
  '/portafolio/cripto': typeof PortafolioCriptoRoute
  '/portafolio/fondos': typeof PortafolioFondosRoute
  '/portafolio/renta-fija': typeof PortafolioRentaFijaRoute
  '/portafolio/': typeof PortafolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/cuotas'
    | '/onboarding'
    | '/portafolio'
    | '/quick-log'
    | '/tesoreria'
    | '/portafolio/acciones'
    | '/portafolio/ahorros'
    | '/portafolio/cripto'
    | '/portafolio/fondos'
    | '/portafolio/renta-fija'
    | '/portafolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/cuotas'
    | '/onboarding'
    | '/quick-log'
    | '/tesoreria'
    | '/portafolio/acciones'
    | '/portafolio/ahorros'
    | '/portafolio/cripto'
    | '/portafolio/fondos'
    | '/portafolio/renta-fija'
    | '/portafolio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/configuracion'
    | '/cuotas'
    | '/onboarding'
    | '/portafolio'
    | '/quick-log'
    | '/tesoreria'
    | '/portafolio/acciones'
    | '/portafolio/ahorros'
    | '/portafolio/cripto'
    | '/portafolio/fondos'
    | '/portafolio/renta-fija'
    | '/portafolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CuotasRoute: typeof CuotasRoute
  OnboardingRoute: typeof OnboardingRoute
  PortafolioRoute: typeof PortafolioRouteWithChildren
  QuickLogRoute: typeof QuickLogRoute
  TesoreriaRoute: typeof TesoreriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-log': {
      id: '/quick-log'
      path: '/quick-log'
      fullPath: '/quick-log'
      preLoaderRoute: typeof QuickLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuotas': {
      id: '/cuotas'
      path: '/cuotas'
      fullPath: '/cuotas'
      preLoaderRoute: typeof CuotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/': {
      id: '/portafolio/'
      path: '/'
      fullPath: '/portafolio/'
      preLoaderRoute: typeof PortafolioIndexRouteImport
      parentRoute: typeof PortafolioRoute
    }
    '/portafolio/renta-fija': {
      id: '/portafolio/renta-fija'
      path: '/renta-fija'
      fullPath: '/portafolio/renta-fija'
      preLoaderRoute: typeof PortafolioRentaFijaRouteImport
      parentRoute: typeof PortafolioRoute
    }
    '/portafolio/fondos': {
      id: '/portafolio/fondos'
      path: '/fondos'
      fullPath: '/portafolio/fondos'
      preLoaderRoute: typeof PortafolioFondosRouteImport
      parentRoute: typeof PortafolioRoute
    }
    '/portafolio/cripto': {
      id: '/portafolio/cripto'
      path: '/cripto'
      fullPath: '/portafolio/cripto'
      preLoaderRoute: typeof PortafolioCriptoRouteImport
      parentRoute: typeof PortafolioRoute
    }
    '/portafolio/ahorros': {
      id: '/portafolio/ahorros'
      path: '/ahorros'
      fullPath: '/portafolio/ahorros'
      preLoaderRoute: typeof PortafolioAhorrosRouteImport
      parentRoute: typeof PortafolioRoute
    }
    '/portafolio/acciones': {
      id: '/portafolio/acciones'
      path: '/acciones'
      fullPath: '/portafolio/acciones'
      preLoaderRoute: typeof PortafolioAccionesRouteImport
      parentRoute: typeof PortafolioRoute
    }
  }
}

interface PortafolioRouteChildren {
  PortafolioAccionesRoute: typeof PortafolioAccionesRoute
  PortafolioAhorrosRoute: typeof PortafolioAhorrosRoute
  PortafolioCriptoRoute: typeof PortafolioCriptoRoute
  PortafolioFondosRoute: typeof PortafolioFondosRoute
  PortafolioRentaFijaRoute: typeof PortafolioRentaFijaRoute
  PortafolioIndexRoute: typeof PortafolioIndexRoute
}

const PortafolioRouteChildren: PortafolioRouteChildren = {
  PortafolioAccionesRoute: PortafolioAccionesRoute,
  PortafolioAhorrosRoute: PortafolioAhorrosRoute,
  PortafolioCriptoRoute: PortafolioCriptoRoute,
  PortafolioFondosRoute: PortafolioFondosRoute,
  PortafolioRentaFijaRoute: PortafolioRentaFijaRoute,
  PortafolioIndexRoute: PortafolioIndexRoute,
}

const PortafolioRouteWithChildren = PortafolioRoute._addFileChildren(
  PortafolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CuotasRoute: CuotasRoute,
  OnboardingRoute: OnboardingRoute,
  PortafolioRoute: PortafolioRouteWithChildren,
  QuickLogRoute: QuickLogRoute,
  TesoreriaRoute: TesoreriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
